steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - VITE_API_URL=${_VITE_API_URL}
      - -t
      - asia-south1-docker.pkg.dev/mediflow-ai-enterprise/mediflow/frontend:${_IMAGE_TAG}
      - .

images:
  - asia-south1-docker.pkg.dev/mediflow-ai-enterprise/mediflow/frontend:${_IMAGE_TAG}

substitutions:
  _IMAGE_TAG: latest
  _VITE_API_URL: http://api-dev.mediflow.example.com
