steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/mediflow-ai-enterprise/mediflow/backend:${_IMAGE_TAG}
      - .

images:
  - asia-south1-docker.pkg.dev/mediflow-ai-enterprise/mediflow/backend:${_IMAGE_TAG}

substitutions:
  _IMAGE_TAG: latest
