apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false

    jsonData:
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: loki
        tags:
          - service
          - level
      tracesToMetrics:
        datasourceUid: prometheus