{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mediflow-app.secretName" . }}
  labels:
    {{- include "mediflow-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwtSecret: {{ required "secret.jwtSecret is required when secret.existingSecret is empty" .Values.secret.jwtSecret | quote }}
  minioAccessKey: {{ .Values.secret.minioAccessKey | quote }}
  minioSecretKey: {{ .Values.secret.minioSecretKey | quote }}
{{- end }}
